name: 'capstone_dbt_project'
version: '1.0.0'
config-version: 2
profile: 'capstone_dbt_project'

# Project-level configurations
models:
  capstone_dbt_project:
    01_staging:
      materialized: view
      # schema: staging
    02_intermediate:
      materialized: ephemeral
      # schema: intermediate
    03_mart:
      materialized: table
      # schema: marts
      +cluster_by: ["loaded_at"]

# Variables for environment-specific values
vars:
  raw_schema: 'raw'
  staging_schema: 'staging'
  intermediate_schema: 'intermediate'
  marts_schema: 'marts'
  start_date: '2010-01-01'

# Documentation configuration
docs-paths: ["docs"]
asset-paths: ["target/compiled"]